### ISSUE TITLE
HTTPS May not work due to .js app listing on diffrent port

### ISSUE THREAD

**Issue by real-cereal-boy** [UnlimitedBytes/node-web-boilerplate#1]
I have an .htaccess however I tried listing on port 21 and 80 but none seem to work any ideas?

**Comment by UnlimitedBytes** [comment]
If you want https to work properly with most browsers, you need to use port 443 for the HTTPS server. However that you can set the HTTPS Port and it may not work in some environments is not a problem of the boilerplate. In some environments that will come in handy. In any other environment you can just set it to default 443.
